### ISSUE TITLE
parametro data in syncAOO.yaml

### ISSUE THREAD

**Issue by marcocipri** [vintra73/e-service_IPA#2]
per il servizio descritto in /flatversion/daysync/syncAOO.yaml
non sarebbe utile prevedere il parametro in richiesta che definisca il giorno di competenza delle variazioni?
diventa difficile altrimenti gestire il processo e avere coscienza, come fruitore, di non aver perso le variazioni del giorno precedente.

**Comment by marcocipri** [comment]
lo stesso vale per 
syncDDAOO.yaml
syncDDEnte.yaml

etc. etc.

**Comment by vintra73** [comment]
al momento applicato fino a syncPECUOs

ti torna?
